{"product_id": "12170", "page": 1, "page_order": 0, "recommended": true, "date": "2018-02-08", "text": "To start off I've played this many moons ago on PlayStation, was on it so much I knew ever road like the back of my hand!\nSo! You can't get this normally, I had to buy the GTA pack from green man gaming, it's not listed but GTA 1&2 are included in the pack!\nSo let's be honest with this game, it don't work on windows 10 because windows 10 sucks eggs! But thankfully a little tweaking here n there it runs fine! It's not the best graphics by today's standards n yes it did take me about 2seconds to download it n yes my wife calls me stupid for spending \u00a32k+ on my pc to end up playing old classic like this! But I'm happy n it's good to blast down the roads n have a shoot out! It's worth going back to this game in my eyes, it will never truly get old!", "hours": 7.0, "user_id": "76561198027858109", "username": "TheGhost", "products": 513, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 1, "recommended": true, "date": "2018-01-18", "text": "I played it for a bit, but I'm not really sure yet if I like it or not.\nI'm going to give it a benefit of the doubt for now and give it a thumps up.", "hours": 474.6, "username": "madmax", "products": 54, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 2, "recommended": true, "date": "2018-01-04", "text": "great classic and it just plays great", "hours": 0.1, "user_id": "76561198023491401", "username": "MR_SERENITY", "products": 149, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 3, "recommended": true, "date": "2017-12-07", "text": "Backlog review, going back to the games I loved the hell out of, or hated, and played pirated copies back in the day or legit ones.\nGTA was the start of it all, played back in the day, highly suggested!", "hours": 0.2, "username": "Ingenium", "products": 610, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 4, "recommended": true, "date": "2017-11-23", "text": "Bueno", "hours": 1.4, "username": "Bobdacious", "products": 315, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 5, "recommended": true, "date": "2017-11-23", "text": "WOW. Great memories with this one. Fav game series of all time. Every time I randomly end up playing this after all the years, it still is great.", "hours": 5.1, "username": "ounaazh", "products": 62, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 6, "recommended": true, "date": "2017-11-23", "text": "The stuff you do for a badge... :/\nBest game ever... :D\nGouranga!!!! In the Beast GTS or the Cossie!\nskrrrra pap pap cla cla cla skiddikipapap and the br br brrr boom skyyya du du ku ku du doom poom poom!", "hours": 0.2, "user_id": "76561197975169619", "username": "<(o.O)>Fezarella^", "products": 67, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 7, "recommended": false, "date": "2017-11-18", "text": "doesn t even work on win.10", "hours": 0.6, "user_id": "76561197963509096", "username": "BigHit", "products": 107, "found_funny": 10, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 8, "recommended": true, "date": "2017-11-14", "text": "My favorite game series.", "hours": 0.1, "username": "Christyna64", "products": 293, "early_access": false}
{"product_id": "12170", "page": 1, "page_order": 9, "recommended": true, "date": "2017-11-10", "text": "ok", "hours": 0.1, "user_id": "76561198073092169", "username": "Wungle", "products": 620, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 0, "recommended": false, "date": "2017-11-07", "text": "Frame-rate stutters too much to be playable. I can't seem to find any fixes for it.", "hours": 0.8, "user_id": "76561197967902818", "username": "Polskie Ogorki", "products": 70, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 1, "recommended": true, "date": "2017-10-03", "text": "Great game", "hours": 2.4, "username": "NinjaPC", "products": 121, "found_funny": 5, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 2, "recommended": false, "date": "2017-09-30", "text": "Tried to put up with the graphical glitches, colours all over the place but couldn't.", "hours": 1.3, "username": "exoticCentipede", "products": 474, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 3, "recommended": true, "date": "2017-09-28", "text": "Love it ! Old Days !", "hours": 6.4, "username": "DragonPC", "products": 1275, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 4, "recommended": false, "date": "2017-09-20", "text": "The game is unplayable... Loading crash after character select. And if you pass through, graphic are glitchy and framerate is like 3 FPS max with a Intel i7, nVidia 970 and 16Gb RAM... this should be remove from steam", "hours": 0.3, "username": "Warface", "products": 210, "found_funny": 7, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 5, "recommended": false, "date": "2017-09-10", "text": "Tried, but couldn't get into it.  Mechanics and perspective were too annoying for me.  This might have been entertaining back in the day but I would (and did) skip to GTA 3.\n3/10", "hours": 0.4, "user_id": "76561198036187439", "username": "gspot19", "products": 1105, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 6, "recommended": false, "date": "2017-08-28", "text": "Unplayable in its current form (Win 10), wish they fix it, since it's an absolute classic.", "hours": 0.2, "user_id": "76561197994684276", "username": "NevznachaY", "products": 1095, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 7, "recommended": false, "date": "2017-08-21", "text": "It did start it all but it's not that great. Gamplay is horrible and difficulty scaling too. And the only objective is to get x money. You can just go to the docks and sell cars to win the level. Also, the story is non-existent and the voice-acting is garbage.", "hours": 0.6, "username": "Cross", "products": 636, "found_funny": 7, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 8, "recommended": true, "date": "2017-07-14", "text": "Still an awesome game, but when I try to run it now, the screen flickers non stop, anyone have a fix for this?", "hours": 3.8, "user_id": "76561197997416991", "username": "Evelyn", "products": 107, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 2, "page_order": 9, "recommended": false, "date": "2017-06-19", "text": "The base GTA  game gives you 20-30 hours experience. I do enjoy the old school matchup on LAN but the old archaic controls are super old now.\nNew players may have a hard time playing this classic including those older Resident Evil games just due to control alone. It still has not been patched to be directional - go where you point, but instead uses a first person control system (forward, turn left or right) but in a top down view.\nIt is atrocious to replay it like this!\nHowever, it has an amazingly fun sense of humor not found outside of the GTA franchise. If you do not mind the outdate un-intuitive controls, you might have a good time going through the story.\nHowever, I have to post my rant on why I would not recommend anyone to buy this:\nI love R* and all the Grand Theft Auto family of games, but lets be real here. R* banned all modding recently in their nuclear management decision to curb cheating in their more modern GTA franchise starting with OpenIV. With OpenIV, modders and the Grand Theft Auto Community, you have a game that can be played for years in SP mode for GTA4 and 5.\nWhen Take Two (publisher) decides to monetize on that goodwill withOUT creating any additional content or assets for the SP user base, trying to force those user online and destory it at the same time, I cannot recommend ANYONE to put their hard earn money into buying ANY Take Two Published games.\nIt is exactly like a politician taking away your RIGHTS - RIGHTS mean something that you have with no questions asked - since modding and OpenIV does not HARM the purchaser, publisher or online experience whatsoever. The mods ONLY work in single player. It is absolutely one of the main reason gamers even buy GTA in the first place.\nAgain for the reading impared, OpenIV CANNOT and does NOT allow any of its modded contented to be used online or interact with that post apocalyptic Detroit where no Robocop can be found they call GTAO.\nBefore anyone disputes this, lookup what OpenIV actually DOES, and note there are CONSUMER FAIR USE LAWS in most IP protected countries that allows private modding for personal use.\nSo NO, I do not recommend anyone to buy ANY Take Two published games including GTA series from R* until they change their shill corporate policy towards the community that built them in the first place.\nIf I can I would REFUND all my Take Two published games and delete it off my HD right away.", "hours": 0.1, "user_id": "76561198019292264", "username": "Valken", "products": 130, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 0, "recommended": true, "date": "2017-06-14", "text": "A classic, but also a very good game. Loads of fun running around the cities causing destruction. The missions are nice and the dialogue is very funny. Don't expect GTA V levels of immersion, this is a top-down arcade game with guns and cars. Look for\nto find a version with the expansion packs and solid framerate on Windows 10.", "hours": 0.1, "user_id": "76561198063265678", "username": "mdmister", "products": 479, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 1, "recommended": false, "date": "2017-05-17", "text": "I remember playing this game at school and it was always awesome. Playing it now.. kinda sucks... just too outdated for me.", "hours": 1.0, "user_id": "76561198066297471", "username": "Umzingeli", "products": 154, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 2, "recommended": true, "date": "2017-05-05", "text": "Still the best Grand Theft Auto game.", "hours": 0.5, "username": "Old Snake", "products": 374, "found_funny": 17, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 3, "recommended": true, "date": "2017-04-08", "text": "", "hours": 0.1, "user_id": "76561198046675266", "username": "Dustin", "products": 1407, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 4, "recommended": true, "date": "2017-02-17", "text": "I used to love this game as a kid so I was really excited when I recently found it for purchase.\nUnfortunately, because of Windows 10, it runs about as smoothly as Forrest Gump before he broke free from his leg braces.", "hours": 0.2, "user_id": "76561198170465054", "username": "Captain Slippy Fist", "products": 246, "found_funny": 23, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 5, "recommended": false, "date": "2017-02-10", "text": "bad", "hours": 0.3, "username": "Mungo", "products": 140, "found_funny": 6, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 6, "recommended": false, "date": "2017-01-31", "text": "Grand Theft Auto:\nSome games are better left forgotten...\nRemember when GTA II first came out on playstation in the 90s? I do. I recall being sick, so I couldn't attend school. I sat in the living room playing Grand Theft Auto II - and boy was it glorious!\nThis game is the predecessor, GTA.\nI decided that 20 years later I should give it a try, with all those fond memories of GTA II. Let me tell you, this game is NOT GREAT and for that matter, neither is GTA II - not anymore - they used to be.\nThrough my nostalgia, I still thought they were.\n+ Good childhood memories, which I guess is always important.\n- Disgusting graphics, birds eye view obstructs vision of anywhere you drive or run.\n- No story, no clear objectives, difficult to complete missions (due to the flaws of the game).\n- Rampages and killing is not fun, nothing is fun in this game!\nGTA is simply too old to be enjoyable. It's a product of its time - a gem when released. Sadly, being a 2D game means it has no place in modern gaming and its replay value is essentially zero.\nValve no longer sells it anyway, so this review is just for the lols.\n2/10", "hours": 15.0, "username": "Vladimir Vladimirovich Putin", "products": 107, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 7, "recommended": true, "date": "2016-11-28", "text": "Fast action, dark humor, and machineguns... What else do you need to have a fun game?", "hours": 0.5, "username": "Lord Chango", "products": 148, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 8, "recommended": true, "date": "2016-11-24", "text": "This fiend never be forgotten", "hours": 0.6, "username": "IP24", "products": 116, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 3, "page_order": 9, "recommended": true, "date": "2016-11-06", "text": "Bubba has the best Storyline, Modern Graphics at its finest, fine holiday fun, and good for the whole family! I approve this message.", "hours": 0.1, "username": "Son of Riggnarok", "products": 122, "found_funny": 8, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 0, "recommended": true, "date": "2016-09-24", "text": "10/10", "hours": 0.5, "username": "Acer....", "products": 120, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 1, "recommended": true, "date": "2016-09-21", "text": "If you somehow find this game somewhere then GET IT and then (If you don't already have that) get a computer that can run it...  I played this long before I got Steam and I still think its better then most new games.", "hours": 0.3, "username": "CSBN-GG", "products": 728, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 2, "recommended": false, "date": "2016-09-06", "text": "I loved the original game, but unfortunately on modern PCs this version of GTA does not run well at all.", "hours": 0.1, "user_id": "76561198034386536", "username": "drshorty03", "products": 74, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 3, "recommended": true, "date": "2016-08-28", "text": "This game bring's back soo many memories, i have a laptop that it doesnt really work and i have a desktop that runs the game fine so it runs good depending on your computer. i rate this 9/11", "hours": 0.1, "username": "Jclar371", "products": 251, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 4, "recommended": true, "date": "2016-07-25", "text": "this game is horrible. but i remember liking it when i was a kid.", "hours": 0.5, "username": "Milk Jug", "products": 355, "found_funny": 4, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 5, "recommended": true, "date": "2016-07-08", "text": "To be honest, I was never a big fan of first Grand Theft Auto game. Maybe I was a little too young to understand how to take missions, back then I also didn't understand much of english. So, the only thing I was doing was driving around, killing people and jumping on THAT bridge. It was probably enought for me to have fun. Not sure how much time spend playing like that but I know one thing - it didn't lasted that long for sure. There were many good games around that time so I probably moved to another game.\nAfter years, I wanted to give first GTA game another try. Finished some missions, played around for some time and, at least for now, no more. First of all, this game is really hard compared to other games in series. You can't save game after mission - you need to get way too much cash if you want to \"save\" your progress and move to next level. Does that mean it's no fun at all? NO. It's really fun. I probably enjoyed it more than newest Grand Theft Auto games. It's kind of game made purely for fun. Also, that main theme song (Joyride by Da Shootaz) is my second favorite one in whole series, it's so great. There is only one thing that I'm kinda of mad at - Rockstar never released mission packs (London 1969 and London 1961) on Steam. For what reason? I'm not sure. Since they brought back Steam pages for both first and second Grand Theft Auto games, maybe one day they will do something about those addons... at least I hope so.\nAt the moment I'm making this review, there is no way to buy first GTA game on Steam. You can hunt for old GTA Complete Packs on websites which sells games BUT there is no guarantee that it will be included at all. Guess you could also check Steam forums, there are always people who are making info about that. If you are fan of series, if you ever wanted to try it or maybe you played it years ago - doesn't matter, it's worth all the trouble of trying to get it.", "hours": 6.6, "username": "Furrek", "products": 4612, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 6, "recommended": false, "date": "2016-06-01", "text": "This game at the moment does not work for me; well it flickers constantly.  Anyone know how to fix this for Windows 8.1 to Windows 10. GTA 2 works just fine for the moment which is shocking. But if anyone knows feel free to let me know.  I cannot recommend this game until its fixed even though it is a good game.", "hours": 0.1, "username": "Rockiwan", "products": 294, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 7, "recommended": true, "date": "2016-05-27", "text": "Better than Infinte Warfare", "hours": 0.3, "user_id": "76561198089346191", "username": "Arsegne", "products": 48, "found_funny": 493, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 8, "recommended": true, "date": "2016-05-07", "text": "Fun game. Kill frenzy!!!!!", "hours": 81.4, "username": "Goldnuget", "products": 324, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 4, "page_order": 9, "recommended": true, "date": "2016-05-01", "text": "Cosworth", "hours": 0.1, "user_id": "76561198031074144", "username": "chris_meredith", "products": 114, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 0, "recommended": true, "date": "2016-04-01", "text": "Gateway game, I played this as a young child, never got off the computer.\nSlept through classes.\n10/10\nWould sleep through school again", "hours": 5.8, "username": "xXx_Immortal-Korean_xXx", "products": 366, "found_funny": 38, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 1, "recommended": true, "date": "2016-03-29", "text": "*UPDATE REVIEW; Well I just played gta and it seems pretty cool although I did have to hop on my windows 7 just to play it but no biggie, so far ive been having fun jacking cars and running over peps so yeah pretty cool getting to play on of the best old school games I highly Recommend 10/10 must play again... 10/10 F#@$5 IGN...", "hours": 0.8, "username": "Chip", "products": 945, "found_funny": 4, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 2, "recommended": true, "date": "2016-03-21", "text": "The gameplay is very straightforward, but it lacks even the most basic of a story line, it just throws you into the game, to kill cops, innocent people, and steal cars, among other things.\nAnswer the phone, drive, run over people, steal cabs, kill cops, sell said stolen cabs. Repeat.", "hours": 14.8, "username": "jjuswell", "products": 262, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 3, "recommended": false, "date": "2016-03-09", "text": "Game is recommended if you like old classics and have a win7 or lower OS, but i could not get it to work on a Win8, Win8.1 or Win10 machine\nheads up!", "hours": 2.6, "username": "Amensis", "products": 193, "found_funny": 4, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 4, "recommended": true, "date": "2016-03-07", "text": "Great", "hours": 0.2, "username": "Blue Uterus", "products": 134, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 5, "recommended": true, "date": "2016-03-02", "text": "Bumped into the leader of a bunch of bald guys in orange, became their leader, led them onto a live rail and set them on fire when they were in the middle of getting fused, doubled my 4X profit for murder. :D", "hours": 1.9, "username": "Retro-Pixel-Lizard", "products": 536, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 6, "recommended": true, "date": "2016-02-17", "text": "It\u2019d be a lie to say GTA1 aged well, but the first entry of the series is still a fun arcade game about carjacking and other criminal activities, with the kind of satiric humour that stood the test of time.\nCompared to the massive open world lumbering giant the franchise grew into, Grand Theft Auto 1 is a simple top-down arcade action game, inspired by the highway car chase helicopter news casts.\nThe simplicity is reflected in the core mechanics: instead of playing through a story (which this game lacks pretty much entirely), all six levels require a target score to pass. While almost every action gives points, the intended way to progress is to raise the score multiplier, usually by completing missions. These missions are barely anything more than a random set of objectives, tied together with some immature and politically incorrect, yet not too controversial flavour text with some (black) humour and social satire.\nThe game is easy in many regards\u2013 enemies aim terribly, the police are quite ineffective, and all tasks can be described in a few words\u2013 but many small annoyances can ruin gameplay. For example, there are no mission retries, and when even the player dies in one hit, it is easy to fail a task on the first try.\nThe best way to approach GTA1 is to think it as a memorisation game: learn the city layouts, weapon locations, and the mission objectives, and it\u2019ll go smoothly. Just don\u2019t forget that there is no save, so each stage has to be completed in one sitting.\nThe game engine is ancient and difficult to run on any modern system. On top of that, it can cause nausea with the jerky camera movement and wonky frame rates. And when it works, the player can enjoy the interesting physics that turn every vehicle into a bouncy bumper car.\nStill, if you can live with these limitations, GTA1 can still hold itself on its own as a good arcade game that can warrant a replay from time to time.", "hours": 16.2, "username": "talgaby", "products": 488, "found_funny": 8, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 7, "recommended": true, "date": "2016-02-05", "text": "You want realism? Here you can die from 1 single shot!\nThe game that started it all. Where you can burp and fart your way around Liberty City, Vice City and San Andreas while hoping you don't crash against a building or another vehicle because the camera doesn't zoom out far enough.\nFollow the -not so- intuitive arrow though the city to find and do the missions your bosses demands and rise your point counter in order to progress to the next city.\nBlow up\u2665\u2665\u2665\u2665\u2665\u2665 kill pedestrians and maybe... JUST MAYBE... You will find those Hare Krishnas and achieve the all mighty GOURANGA!", "hours": 10.1, "username": "Rufi", "products": 762, "found_funny": 9, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 8, "recommended": true, "date": "2016-01-21", "text": "It doesn't have Shark Cards. It also doesn't make you buy cars.", "hours": 0.3, "username": "Mega", "products": 434, "found_funny": 131, "early_access": false}
{"product_id": "12170", "page": 5, "page_order": 9, "recommended": true, "date": "2015-12-28", "text": "FARTS all day long!", "hours": 1.1, "username": "schnabear", "products": 133, "found_funny": 40, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 0, "recommended": true, "date": "2015-12-14", "text": "Grand Theft Auto is now old enough to play Grand Theft Auto.", "hours": 13.3, "username": "Jerboa", "products": 2073, "found_funny": 591, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 1, "recommended": false, "date": "2015-12-07", "text": "Laggs", "hours": 1.7, "username": "Mkvarner", "products": 71, "found_funny": 13, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 2, "recommended": true, "date": "2015-11-14", "text": "Best GTA ever! There was no Grand Theft Auto since then, that was this fun!", "hours": 0.2, "username": "4d 69 72 65 6b | \u30df\u30ec\u30af", "products": 1364, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 3, "recommended": true, "date": "2015-11-13", "text": "BUSTEEEED.\nSHOTGUUUUN.\nThe sounds in game should be modded over to gta v.", "hours": 0.1, "username": "Ave", "products": 1020, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 4, "recommended": true, "date": "2013-04-29", "text": "This game is like hardcore GTA. one shot one kill, for both you and others unless body armor is worn, its 4 shots 1 kill. No saves, so you die too many times, you lose and have to start over form scratch. Missions are pretty simple, no money system, but points system that acts like money. sports/morobikes are too fast to even drive, so you will most likely crash to everything. no minimap so you will get lost most often. This game is pretty okay for a old game, but I just can't play a game with no minimap or some type of map. 6/10", "hours": 1.4, "username": "\u239b\u239dGoldberg\u23a0\u239e", "products": 503, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 5, "recommended": true, "date": "2013-04-27", "text": "SUCH A FUN OLD CLASSIC!:)", "hours": 16.3, "username": "Hiko The Magical Wizard", "products": 482, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 6, "recommended": true, "date": "2013-04-11", "text": "Where it all began.", "hours": 0.3, "user_id": "76561198031682928", "username": "Garpil", "products": 43, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 7, "recommended": true, "date": "2013-04-07", "text": "A classic of Classics", "hours": 0.6, "username": "Rammsteniako", "products": 1644, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 8, "recommended": true, "date": "2013-04-06", "text": "This is not a particularly good game. Without it, we would not have had the most influential game since Doom. That means this is worth playing, as a historical piece, to see the strange birthing chamber that would eventually produce our horrible open-world present.\nYou'll get sick of it in five minutes.", "hours": 0.1, "username": "CarlCX", "products": 2373, "early_access": false}
{"product_id": "12170", "page": 6, "page_order": 9, "recommended": true, "date": "2013-03-29", "text": "\u00c9 pra quem \u00e9 f\u00e3n do GTA mesmo, os gr\u00e1ficos n\u00e3o s\u00e3o la essa coisas :)", "hours": 0.0, "username": "Angel Wars", "products": 37, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 0, "recommended": true, "date": "2013-03-25", "text": "Great game. X)", "hours": 0.4, "user_id": "76561198022336820", "username": "eroeru", "products": 1098, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 1, "recommended": true, "date": "2013-01-18", "text": "Grand Theft Auto (\u0441\u043e\u043a\u0440\u0430\u0449\u0451\u043d\u043d\u043e \u2014 GTA) \u2014 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u043d\u0430\u044f \u0438 \u0432\u0438\u0434\u0435\u043e\u0438\u0433\u0440\u0430, \u043f\u0435\u0440\u0432\u0430\u044f \u0447\u0430\u0441\u0442\u044c \u0438\u0437\u0432\u0435\u0441\u0442\u043d\u043e\u0439 \u0441\u0435\u0440\u0438\u0438 Grand Theft Auto.\n\u0412 \u0438\u0433\u0440\u0435 \u0438\u0433\u0440\u043e\u043a\u0443 \u043f\u0440\u0435\u0434\u0441\u0442\u043e\u0438\u0442 \u0432\u0437\u044f\u0442\u044c \u043d\u0430 \u0441\u0435\u0431\u044f \u0440\u043e\u043b\u044c \u043f\u0440\u0435\u0441\u0442\u0443\u043f\u043d\u0438\u043a\u0430, \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u043c\u043e\u0436\u0435\u0442 \u0441\u0432\u043e\u0431\u043e\u0434\u043d\u043e \u043f\u0435\u0440\u0435\u043c\u0435\u0449\u0430\u0442\u044c\u0441\u044f \u043f\u043e \u0433\u043e\u0440\u043e\u0434\u0443 \u0438 \u0432\u044b\u043f\u043e\u043b\u043d\u044f\u0442\u044c \u0440\u0430\u0437\u043b\u0438\u0447\u043d\u044b\u0435 \u043c\u0438\u0441\u0441\u0438\u0438 \u0438\u043b\u0438 \u043f\u043e\u0440\u0443\u0447\u0435\u043d\u0438\u044f, \u0442\u0430\u043a\u0438\u0435 \u043a\u0430\u043a \u0437\u0430\u043a\u0430\u0437\u043d\u044b\u0435 \u0443\u0431\u0438\u0439\u0441\u0442\u0432\u0430 \u0438 \u0434\u0440\u0443\u0433\u0438\u0435 \u043f\u0440\u0435\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f.", "username": "CRanKy SPaRk", "products": 1865, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 2, "recommended": true, "date": "2013-01-17", "text": "Nostalgia makes any \u2665\u2665\u2665\u2665\u2665\u2665 game golden, and boy is this turd shiny!", "username": "Carlos Danger", "products": 777, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 3, "recommended": true, "date": "2013-01-07", "text": "nostalgia epic <3", "hours": 46.1, "username": "xaxinator", "products": 191, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 4, "recommended": true, "date": "2012-12-31", "text": "I'm kinda astounded as to how this game got a sequel. I was squelching around corners and practically barfing at the forced perspective the buildings made. GTA 2 was better, still has the perspective though. Start there. 1 is pretty much purely for nostalgia.", "hours": 0.3, "username": "Dirty Dan the despicable(Oculus)", "products": 1087, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 5, "recommended": true, "date": "2012-12-30", "text": "If you really want to blast to the past as far as GTA goes, I would recommend playing GTA2, as it has many improvements over the original GTA.  This is still a great game, though I was disappointed that the Steam release did not include GTA: London or any of the other expansion packs.  Those content sets really brought in some great humor to the series, which was later refined in GTA2.", "hours": 0.0, "username": "angrysquare", "products": 503, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 6, "recommended": true, "date": "2012-12-30", "text": "Old skool GTA! I played this sucker non-stop back in the days.\nIts sad that todays PC's are to fast to run this game and you are forced to use the Frame Rate Limiter which makes the frame rate just to low to enjoy this great classic.", "hours": 0.1, "username": "Spitfire", "products": 928, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 7, "recommended": true, "date": "2012-11-23", "text": "[?/10]  (all you need to know is GTA series always better than any other games)\nGrand Theft Auto, best game Series in human history. Thank you, Rockstar Games.", "hours": 13.1, "username": "Stanley Ipkiss", "products": 1677, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 8, "recommended": true, "date": "2012-08-21", "text": "Oldies but goldies :)", "hours": 12.2, "username": "CapShot", "products": 2623, "early_access": false}
{"product_id": "12170", "page": 7, "page_order": 9, "recommended": true, "date": "2012-08-15", "text": "LOL - Pique", "hours": 0.9, "user_id": "76561198068072919", "username": "Nikolai", "products": 112, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 0, "recommended": false, "date": "2012-07-21", "text": "Sometimes we like to play the original games of successful franchises so that we can appreciate where they all began, but this isn't worth it in the slightest. Bad game.", "hours": 0.1, "username": "Roxas", "products": 539, "found_funny": 6, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 1, "recommended": true, "date": "2012-07-20", "text": "Best game ever... No, really. I mean it. It is the best. That feeling when you slaughter entire group of Hare Krishna monks and it goes like GOURANGA ... Oh nostalgia. Good times, good times...", "hours": 0.1, "username": "IndianaJaws", "products": 434, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 2, "recommended": true, "date": "2012-07-19", "text": "Great game for its time. Frustrating to play on today's advancements. 4/10", "hours": 0.1, "username": "Vel", "products": 532, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 3, "recommended": true, "date": "2012-07-18", "text": "la base ..", "hours": 3.0, "user_id": "76561197961183467", "username": "AttenTA", "products": 82, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 4, "recommended": true, "date": "2012-07-18", "text": "The original and my opinion still the best GTA game.  If you have not played it before what are you waiting for?  It is only a couple of quid and is a very important part of gaming history if nothing else.", "hours": 0.4, "username": "Puppet", "products": 393, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 5, "recommended": true, "date": "2012-07-15", "text": "hehe", "hours": 0.2, "username": "mmartinn", "products": 438, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 6, "recommended": true, "date": "2012-07-06", "text": "Take it to the edge, there's nowhere to hide\nAnd call up the boys, let's go for a joyride", "username": "cage", "products": 139, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 7, "recommended": true, "date": "2012-06-18", "text": "Grand Theft Auto is the root of open world exploration and gameplay. Released in 1998, this classic title started jump started the future for gaming. I don\u2019t recommend this game just because it\u2019s classic, I recommend it because it genuinely has good gameplay. The world is rather large for a game of the late 90s, and gameplay is actually better than a lot of Indies of today. Multiple mission routes mean endless replay value. If you\u2019re not the type to follow story, just go around stealing cars and killing \u2665\u2665\u2665\u2665\u2665es, hoes, and pedestrians for mad points. It\u2019s a real shame the developers gimped on the graphics of Grand Theft Auto. Even for a late 90\u2019s game, the graphics for Grand Theft Auto is god awful. When my avatar leaves his car, I can\u2019t tell the difference between his front and backside; this makes shooting quite chaotic and confusing at times. If you look pass the graphics, there is lots of fun to be had from this classic title. Play it.", "hours": 11.2, "username": "amBADatgames", "products": 5168, "found_funny": 15, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 8, "recommended": true, "date": "2012-04-28", "text": "The graphics are unbelievable! Such realism!", "hours": 0.1, "user_id": "76561198019720215", "username": "[RadMerc] BlazingIceZ", "products": 107, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 8, "page_order": 9, "recommended": true, "date": "2012-03-31", "text": "If you can get this game to work or part 2, they are totally a blast to play!  I remember the just running drugs, hitting up on gangs, and out running the cops!  Unfortunatley the new GTA games do not make you feel the same way this one did... the closest GTA to the original is San Andreas.\nBascially you meet people or answer the phone in this top down view mission based game but in a open world situation.", "username": "McMillanFixXxeR", "products": 414, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 0, "recommended": true, "date": "2012-02-19", "text": "Graphics will dissapoint the \"PC MASTER RACE\", but i recommend this game to people capable of using their brain.", "hours": 1.3, "username": "PolisKanin", "products": 107, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 1, "recommended": true, "date": "2012-01-04", "text": "If I have to even recommend this top town classic which started it all to you,then you should be shot,dragged,smacked in the face closed fist style, and beat in the face with a well glazed  honey ham.", "hours": 0.2, "username": "General Cha\u00f8s\u2122", "products": 799, "found_funny": 2, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 2, "recommended": true, "date": "2012-01-03", "text": "I recommend the original Grand Theft Auto because I fear many haven't played it, or even more worryingly may believe GTA III to be the first actual installment. GTA was one of the first games I played on PC and while it lacks the 3D graphics of today's era it is still tons of fun. The modern iterations of the GTA franchise focus too heavily on story and never on an arcade pick-up-and-play style game. GTA was just that. It's fun, pure and simple.", "hours": 0.6, "username": "TheMooDude", "products": 339, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 3, "recommended": true, "date": "2012-01-03", "text": "HOLY\u2665\u2665\u2665\u2665\u2665\u2665ITS THE NINTEIES!", "hours": 0.0, "username": "V-Man", "products": 564, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 4, "recommended": true, "date": "2011-12-31", "text": "the first but still good", "hours": 5.0, "user_id": "76561198055520226", "username": "pyromaniac247", "products": 115, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 5, "recommended": true, "date": "2011-12-30", "text": "G, Grand Theft Auto. Bringing crime to the masses, in a fun way.", "hours": 0.2, "username": "Daveoh", "products": 388, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 6, "recommended": true, "date": "2011-12-27", "text": "must have!", "hours": 0.0, "username": "LeFok", "products": 1215, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 7, "recommended": true, "date": "2011-12-25", "text": "14 years after its initial release, still ALLOT of fun. Not many games have achieved that.", "hours": 4.3, "username": "freemmaann", "products": 187, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 8, "recommended": true, "date": "2011-12-23", "text": "The classic, the one, the only, GTA. This is free to play off the Rockstar Classics site - so no doubt get it for free if possible, but this really started open world gaming. You need a set million X points to progress - get it with missions (easiest way) or by doing whatever you want - police are agressive, top down view is fast and frentic, and it is damn hard in later levels! Wonderful stuff, then and mostly now.", "hours": 0.1, "username": "Finaldeath", "products": 623, "early_access": false}
{"product_id": "12170", "page": 9, "page_order": 9, "recommended": true, "date": "2011-12-15", "text": "The most controversial game after Carmageddon :P", "hours": 58.5, "username": "GasMask", "products": 3146, "found_funny": 9, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 0, "recommended": true, "date": "2011-12-13", "text": "Its \u2665\u2665\u2665\u2665\u2665in'", "username": "XARDONIAK", "products": 171, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 1, "recommended": true, "date": "2011-12-03", "text": "GTA1 is a PC classic by now. The first two GTA games are both in a 2D top-down style. The gameplay resembles what you'd expect to find in any Grand Theft Auto game: steal cars, run down pedestrians, and evade the police. The difference is that this game offers very little else. There's a very loose mission structure, but really very little reason to care about them. This game truly is a sandbox, which can be fun to play around in, but the lack of direction prevents it from holding your attention for too long.\nThe graphics are decent for the time. The sound can get obnoxious quickly, and there's no music. The controls aren't very good, and I found it imposible to play with a controller.\nAt the very least, the price is right. You can't buy it individually on Steam, but it's free on Rockstar's website.", "hours": 0.0, "username": "UjuidarEhcram", "products": 1154, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 2, "recommended": true, "date": "2011-12-02", "text": "Cant go wrong with the game that started it all", "hours": 0.1, "user_id": "76561197985502086", "username": "Zapher", "products": 862, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 3, "recommended": true, "date": "2011-11-30", "text": "Such a good game", "hours": 0.1, "username": "Vexparadox", "products": 235, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 4, "recommended": true, "date": "2011-11-26", "text": "OH yea! GET IT AND FEEL IT !!", "hours": 0.2, "user_id": "76561198044751182", "username": "TheMoust", "products": 392, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 5, "recommended": true, "date": "2011-11-25", "text": "this game is like playing dr. jekyl and mr. hyde. its like trying to kill godzilla while whacking him with your flacid\u2665\u2665\u2665\u2665\u2665\u2665", "hours": 0.0, "username": "DA KILLBOY", "products": 277, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 6, "recommended": true, "date": "2011-11-01", "text": "plaed a few minutes, and it didn't seem like my type of gang. Maybe its a classic, but I really didn't want this and 2 in the first place, but it came with the pack...", "hours": 0.0, "user_id": "76561198043660467", "username": "Zemoco101", "products": 308, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 7, "recommended": true, "date": "2011-10-25", "text": "I played this when I was 5.", "hours": 1.7, "username": "Gliv Gluv", "products": 632, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 8, "recommended": true, "date": "2011-10-21", "text": "Press Tab everyday", "hours": 0.2, "username": "Annie T. Mood", "products": 1091, "early_access": false}
{"product_id": "12170", "page": 10, "page_order": 9, "recommended": true, "date": "2011-10-13", "text": "A must have! Best graphics I've experienced in a while, and the camera controls (1) are amazing! And the storyline is completely logical! It also has wonderful music, and the pager is very useful. The pimp missions are great for young children!", "hours": 11.7, "username": "Wildfire", "products": 643, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 0, "recommended": true, "date": "2011-10-04", "text": "Originally played this when it came out on PS1 and it absolutely blew my 6 year old mind away. Great game but does not currently run well on newer computers.", "hours": 0.6, "username": "REDD", "products": 359, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 1, "recommended": true, "date": "2011-09-24", "text": "The game itself is actually free, so the savings are passed on to YOU.", "hours": 0.2, "username": "icollectsponges", "products": 165, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 2, "recommended": true, "date": "2011-08-02", "text": "Dont get it.", "hours": 0.0, "user_id": "76561198043164018", "username": "Troll Ghost", "products": 155, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 3, "recommended": true, "date": "2011-07-05", "text": "While a lot of people seemed to have first played the GTA series with the 3rd person games, I started here. It's a terrific, humorous action game without the involved stories of the newer ones.", "hours": 13.8, "username": "TheUser", "products": 202, "found_funny": 9, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 4, "recommended": true, "date": "2011-07-05", "text": "this game teaches young children to steal cars", "username": "Communist \"Joseph Ballin\" Layton", "products": 1177, "found_funny": 8, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 5, "recommended": true, "date": "2011-07-04", "text": "PIECE OF\u2665\u2665\u2665\u2665\u2665", "hours": 0.6, "username": "comrade barbie", "products": 513, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 6, "recommended": true, "date": "2011-07-04", "text": "Man! How I love this game! It brings me some sweet memories :)\nBesides that, this game is so much fun. Give it a try. You can get it for free on the Rockstars website :D", "hours": 0.1, "username": "Jef", "products": 838, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 7, "recommended": true, "date": "2011-07-03", "text": "GRRRRRRRRRRRRRRRAND THEFT AUTO\nAnyway. Both this game and GTA2 were taken off the Steam store, likely due to licensing shenanigans on Rockstar's part. This also means that you cannot create new reviews of either game. Lucky for me, I posted a joke review years ago, consisting of that one-liner at the top.\nThe game itself is an old top-down arcade-style open-world game where you must complete missions and wreak havoc to gain points. Each city has two 'levels' containing missions, and you can only save at the end of each level. Once you get enough points you can advance to the next level. Liberty City, Vice City and Los Santos all make their debut in this game. The controls can be difficult, and when you're driving, the car and camera often move too fast for you to react to obstacles.\nThis isn't exactly a stellar game, but it's interesting to witness the birth of GTA, even though it wouldn't assume the form we know it as now until GTA III was released. The main menu is deliciously '90s, at least. If you consider yourself a game history buff or a connoisseur of old games, try this one out if you can find it.", "hours": 0.2, "username": "Trar", "products": 388, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 8, "recommended": false, "date": "2011-07-01", "text": "DO NOT PLAY.  YOU WILL HATE IT.  TOTAL BORE, TOP DOWN VIEW.", "username": "Anewbis", "products": 129, "found_funny": 19, "early_access": false}
{"product_id": "12170", "page": 11, "page_order": 9, "recommended": true, "date": "2011-04-30", "text": "nessa epoca, gta era jogo de caucasiano", "hours": 0.5, "username": "Sentafria", "products": 736, "early_access": false}
{"product_id": "12170", "page": 12, "page_order": 0, "recommended": true, "date": "2011-04-24", "text": "Old but good!", "hours": 1.5, "username": "Papai WoverH'", "products": 290, "found_funny": 3, "early_access": false}
{"product_id": "12170", "page": 12, "page_order": 1, "recommended": true, "date": "2011-02-28", "text": "Classic", "hours": 0.2, "user_id": "76561198020573756", "username": "Ninan Pitu Nanu", "products": 377, "early_access": false}
{"product_id": "12170", "page": 12, "page_order": 2, "recommended": true, "date": "2011-02-20", "text": "Makes me wish that Carmageddon got a reboot.  Stupid, amoral fun.", "hours": 0.9, "username": "Monchberter: here for airshots", "products": 259, "early_access": false}
{"product_id": "12170", "page": 12, "page_order": 3, "recommended": true, "date": "2011-02-19", "text": "The one that started it all - and I mean getting the editor of the Daily Mail to threaten to resign if the game wasn't banned. Four games later, the GTA series succeeded. Back to the original, witness (read: cause) such atrocities like 'Gouranga': achieved by running down lines of Hare Krishna monks. Beg, kill, steal, and cheat your way into avoiding cops to earn your cool million bucks. Then get out of town as fast as you can... crime just isn't what it used to be.", "hours": 0.1, "username": "PaulusMaximus1983", "products": 375, "found_funny": 1, "early_access": false}
{"product_id": "12170", "page": 12, "page_order": 4, "recommended": true, "date": "2011-01-22", "text": "The controls on this game suck\u2665\u2665\u2665\u2665\u2665 but hey, it's FREE.  I tried this game with a controller thinking maybe it'd be better, only it got worse. Anyway, my recommendation for this game is to avoid it unless you're bored, have nostalgia goggles to go with it, or unless you've found some way to make the controls worth it, in which case, TELL ME.", "hours": 1.4, "username": "arleas", "products": 2113, "early_access": false}
{"product_id": "12170", "page": 12, "page_order": 5, "recommended": true, "date": "2010-12-23", "text": "A controversial classic which flourished into something yet even MORE controversial.  Has a DOPE soundtrack that you will remember for years to come including all genres.  The best part is the country song, because the lyrics make fun of country songs!  WIN!", "username": "Rumjaku", "products": 1076, "early_access": false}
{"product_id": "12170", "page": 12, "page_order": 6, "recommended": true, "date": "2010-12-12", "text": "One awesome little game that started it all. It only has a top down view that takes a few mins to get adjusted to, but once you get the controls, it is a pretty cool little game. It still has all of the crazy and wackiness as the new ones, and you also have freedom to make money however you want in the city. The only thing is it has the old school like difficulty, and that might turn others off, but I still think this is an awesome game. You can also play it on anything, even a netbook.", "hours": 0.1, "username": "defiance5050", "products": 607, "early_access": false}
{"product_id": "12170", "page": 12, "page_order": 7, "recommended": true, "date": "2010-12-11", "text": "GOURANGA!", "hours": 14.2, "username": "proudlarry", "products": 3163, "found_funny": 7, "early_access": false}
